<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CapFrameX.Service.Analysis\CapFrameX.Service.Analysis.csproj" />
    <ProjectReference Include="..\CapFrameX.Service.Core\CapFrameX.Service.Core.csproj" />
    <ProjectReference Include="..\CapFrameX.Service.Data\CapFrameX.Service.Data.csproj" />
    <ProjectReference Include="..\CapFrameX.Service.Records\CapFrameX.Service.Records.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
