// <auto-generated />
using System;
using CapFrameX.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapFrameX.Service.Data.Migrations
{
    [DbContext(typeof(CapFrameXDbContext))]
    partial class CapFrameXDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CapFrameX.Service.Data.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiInfo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseDriverVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverPackage")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gpu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("GpuCoreClock")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GpuCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GpuDriverVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("GpuMemoryClock")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Hags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Motherboard")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PresentationMode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ResizableBar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolutionInfo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SuiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemRam")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("WinGameMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GameName");

                    b.HasIndex("Gpu");

                    b.HasIndex("ProcessName");

                    b.HasIndex("Processor");

                    b.HasIndex("GameName", "CreatedAt");

                    b.HasIndex("SuiteId", "CreatedAt");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("CapFrameX.Service.Data.Models.SessionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AverageFps")
                        .HasColumnType("REAL");

                    b.Property<double?>("AvgCpuPower")
                        .HasColumnType("REAL");

                    b.Property<double?>("AvgCpuTemp")
                        .HasColumnType("REAL");

                    b.Property<double?>("AvgCpuUsage")
                        .HasColumnType("REAL");

                    b.Property<double?>("AvgGpuPower")
                        .HasColumnType("REAL");

                    b.Property<double?>("AvgGpuTemp")
                        .HasColumnType("REAL");

                    b.Property<double?>("AvgGpuUsage")
                        .HasColumnType("REAL");

                    b.Property<string>("CaptureDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaxFps")
                        .HasColumnType("REAL");

                    b.Property<double?>("MedianFps")
                        .HasColumnType("REAL");

                    b.Property<double?>("P0_01Fps")
                        .HasColumnType("REAL");

                    b.Property<double?>("P0_1Fps")
                        .HasColumnType("REAL");

                    b.Property<double?>("P1Fps")
                        .HasColumnType("REAL");

                    b.Property<double?>("P5Fps")
                        .HasColumnType("REAL");

                    b.Property<double?>("P95Fps")
                        .HasColumnType("REAL");

                    b.Property<double?>("P99Fps")
                        .HasColumnType("REAL");

                    b.Property<string>("PmdCpuPowerJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PmdGpuPowerJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PmdSystemPowerJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresentMonRuntime")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RtssFrameTimesJson")
                        .HasColumnType("TEXT");

                    b.Property<double>("SampleTime")
                        .HasColumnType("REAL");

                    b.Property<string>("SensorDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AverageFps");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("P1Fps");

                    b.HasIndex("P99Fps");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "CreatedAt");

                    b.ToTable("SessionRuns");
                });

            modelBuilder.Entity("CapFrameX.Service.Data.Models.Suite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Type");

                    b.HasIndex("Type", "CreatedAt");

                    b.ToTable("Suites");
                });

            modelBuilder.Entity("CapFrameX.Service.Data.Models.Session", b =>
                {
                    b.HasOne("CapFrameX.Service.Data.Models.Suite", "Suite")
                        .WithMany("Sessions")
                        .HasForeignKey("SuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suite");
                });

            modelBuilder.Entity("CapFrameX.Service.Data.Models.SessionRun", b =>
                {
                    b.HasOne("CapFrameX.Service.Data.Models.Session", "Session")
                        .WithMany("Runs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CapFrameX.Service.Data.Models.Session", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("CapFrameX.Service.Data.Models.Suite", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
