<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
    <RootNamespace>CapFrameX.ApiInterface</RootNamespace>
    <AssemblyName>CapFrameX.Remote</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DryIoc.dll" Version="5.4.3" />
    <PackageReference Include="EmbedIO" Version="3.4.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Serilog" Version="2.9.0" />
    <PackageReference Include="System.Reactive" Version="6.1.0" />
    <PackageReference Include="Unosquare.Swan.Lite" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CapFrameX.Contracts\CapFrameX.Contracts.csproj" />
    <ProjectReference Include="..\CapFrameX.Data\CapFrameX.Data.csproj" />
    <ProjectReference Include="..\CapFrameX.Mcp\CapFrameX.Mcp.csproj" />
    <ProjectReference Include="..\CapFrameX.Monitoring.Contracts\CapFrameX.Monitoring.Contracts.csproj" />
    <ProjectReference Include="..\CapFrameX.PresentMonInterface\CapFrameX.PresentMonInterface.csproj" />
    <ProjectReference Include="..\CapFrameX.Statistics.NetStandard\CapFrameX.Statistics.NetStandard.csproj" />
  </ItemGroup>

</Project>
