<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\CapFrameX.Service.Shared\src\CapFrameX.Service.Core\CapFrameX.Service.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>CapFrameX.Service.Infrastructure</RootNamespace>
    <AssemblyName>CapFrameX.Service.Infrastructure</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
