<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.AspNetCore.Http" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Squidex.ClientLibrary" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="System.Net.Http" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="System.Text.RegularExpressions" />
    <PackageReference Include="System.Threading.Tasks.Extensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CapFrameX.Data.Session\CapFrameX.Data.Session.csproj" />
    <ProjectReference Include="..\CapFrameX.Sensor.Reporting\CapFrameX.Sensor.Reporting.csproj" />
  </ItemGroup>

</Project>
